stock1n=str(input("nome do produto:"))
stock1p=float(input("preço do produto:"))
stock1q=int(input("quantidade em stock:"))
stock2n=str(input("nome do produto:"))
stock2p=float(input("preço do produto:"))
stock2q=int(input("quantidade em stock:"))
stock3n=str(input("nome do produto:"))
stock3p=float(input("preço do produto:"))
stock3q=int(input("quantidade em stock:"))
valortotals1=(stock1p*stock1q)
valortotals2=(stock2p*stock2q)
valortotals3=(stock3p*stock3q)
print("nome:",stock1n,"preço:",stock1p,"quantidade:",stock1q,"valor total é",valortotals1)
print("nome:",stock2n,"preço:",stock2p,"quantidade:",stock2q,"valor total é",valortotals2)
print("nome:",stock2n,"preço:",stock2p,"quantidade:",stock2q,"valor total é",valortotals3)
print("o stock da loja é de",valortotals1+valortotals2+valortotals3)