destino=input("Local que vais:")
distancia=int(input("distancia(km):"))
pcombustivel=int(input("preço do combustivel por litros:"))
lpkm=int(input("quantos litros o carro gasta por 100km:"))
nd=int(input("qual o numero de dias da estadia:"))
pd=int(input("qual é o custo médio diário do hotel:"))
print("\n")
print("\n")
print("destino:",destino)
print("distancia:",distancia)
print("custo do combustivel:",pcombustivel*distancia/lpkm)
print("custo do hotel:",nd*pd)
print("custo total da viagem:",(nd*pd)+(pcombustivel+distancia))
